import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { cn } from '@/lib/utils'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="[color-scheme:dark]">
      <body
        className={cn(
          inter.className,
          'dark min-h-[100dvh] bg-background font-sans antialiased',
        )}
      >
        {children}
      </body>
    </html>
  )
}
